/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness only: never touches the database (D1).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: `SELECT 1` within 2 seconds. For traffic routing, never for
         *     container health, so a database blip can't get every API container killed.
         *
         *     The probe runs as its own task and is waited on, never cancelled: cancelling
         *     a query against a frozen server leaves connection cleanup blocked on that
         *     server, which would hang this endpoint for as long as the outage lasts. At
         *     most one probe is in flight, so repeated checks during an outage can't pile
         *     up connections (D49).
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_v1_services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_api_v1_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service */
        get: operations["get_service_api_v1_services__service_id__get"];
        put?: never;
        post?: never;
        /** Delete Service */
        delete: operations["delete_service_api_v1_services__service_id__delete"];
        options?: never;
        head?: never;
        /** Update Service */
        patch: operations["update_service_api_v1_services__service_id__patch"];
        trace?: never;
    };
    "/api/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deployments */
        get: operations["list_deployments_api_v1_deployments_get"];
        put?: never;
        /** Create Deployment */
        post: operations["create_deployment_api_v1_deployments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{deployment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deployment */
        get: operations["get_deployment_api_v1_deployments__deployment_id__get"];
        put?: never;
        post?: never;
        /** Delete Deployment */
        delete: operations["delete_deployment_api_v1_deployments__deployment_id__delete"];
        options?: never;
        head?: never;
        /** Update Deployment */
        patch: operations["update_deployment_api_v1_deployments__deployment_id__patch"];
        trace?: never;
    };
    "/api/v1/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Failures */
        get: operations["list_failures_api_v1_failures_get"];
        put?: never;
        /** Create Failure */
        post: operations["create_failure_api_v1_failures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/failures/{failure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Failure */
        get: operations["get_failure_api_v1_failures__failure_id__get"];
        put?: never;
        post?: never;
        /** Delete Failure */
        delete: operations["delete_failure_api_v1_failures__failure_id__delete"];
        options?: never;
        head?: never;
        /** Update Failure */
        patch: operations["update_failure_api_v1_failures__failure_id__patch"];
        trace?: never;
    };
    "/api/v1/events/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Deployment Event */
        post: operations["ingest_deployment_event_api_v1_events_deployments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/dora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dora Summary */
        get: operations["dora_summary_api_v1_metrics_dora_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/dora/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dora Timeseries */
        get: operations["dora_timeseries_api_v1_metrics_dora_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChangeFailRate */
        ChangeFailRate: {
            /** Rate */
            rate: number | null;
            /** Failed Deployments */
            failed_deployments: number;
            /** Total Deployments */
            total_deployments: number;
            /** Band */
            band: ("elite" | "high" | "medium" | "low") | null;
        };
        /** ChangeLeadTime */
        ChangeLeadTime: {
            /** Median Hours */
            median_hours: number | null;
            /** P90 Hours */
            p90_hours: number | null;
            /** Sample Size */
            sample_size: number;
            /** Excluded Samples */
            excluded_samples: number;
            /** Band */
            band: ("elite" | "high" | "medium" | "low") | null;
        };
        /** CommitIn */
        CommitIn: {
            /** Sha */
            sha: string;
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
            /** Author */
            author?: string | null;
            /** Message */
            message?: string | null;
        };
        /** CommitOut */
        CommitOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sha */
            sha: string;
            /** Committed At */
            committed_at: string;
            /** Author */
            author: string | null;
            /** Message */
            message: string | null;
        };
        /** DeploymentCreate */
        DeploymentCreate: {
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /**
             * Kind
             * @default planned
             * @enum {string}
             */
            kind: "planned" | "remediation";
            /** Release */
            release: string;
            /** Head Sha */
            head_sha?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "succeeded" | "failed" | "rolled_back";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Deployed By */
            deployed_by?: string | null;
            /** Pipeline Url */
            pipeline_url?: string | null;
            /** External Id */
            external_id?: string | null;
            /** Commits */
            commits?: components["schemas"]["CommitIn"][];
        };
        /** DeploymentDetail */
        DeploymentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /**
             * Kind
             * @enum {string}
             */
            kind: "planned" | "remediation";
            /** Release */
            release: string;
            /** Head Sha */
            head_sha: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "succeeded" | "failed" | "rolled_back";
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Deployed By */
            deployed_by: string | null;
            /** Pipeline Url */
            pipeline_url: string | null;
            /** External Id */
            external_id: string | null;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Commits */
            commits: components["schemas"]["CommitOut"][];
            /** Failures */
            failures: components["schemas"]["FailureSummary"][];
        };
        /**
         * DeploymentEvent
         * @description A pipeline's report of a deployment's state (§7.6).
         *
         *     Identified by (service_slug, external_id). The first event for a pair
         *     creates the deployment; later ones update it. Fields left out of a later
         *     event are left unchanged.
         */
        DeploymentEvent: {
            /** Service Slug */
            service_slug: string;
            /**
             * External Id
             * @description Idempotency key. For GitHub Actions: gha-<run_id>-<run_attempt>-<environment>
             */
            external_id: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /**
             * Kind
             * @default planned
             * @enum {string}
             */
            kind: "planned" | "remediation";
            /** Release */
            release: string;
            /** Head Sha */
            head_sha?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "succeeded" | "failed" | "rolled_back";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Deployed By */
            deployed_by?: string | null;
            /** Pipeline Url */
            pipeline_url?: string | null;
            /** Commits */
            commits?: components["schemas"]["CommitIn"][];
        };
        /** DeploymentFrequency */
        DeploymentFrequency: {
            /** Count */
            count: number;
            /** Per Day */
            per_day: number | null;
            /** Deploy Days */
            deploy_days: number;
            /** Band */
            band: ("elite" | "high" | "medium" | "low") | null;
        };
        /** DeploymentOut */
        DeploymentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /**
             * Kind
             * @enum {string}
             */
            kind: "planned" | "remediation";
            /** Release */
            release: string;
            /** Head Sha */
            head_sha: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "succeeded" | "failed" | "rolled_back";
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Deployed By */
            deployed_by: string | null;
            /** Pipeline Url */
            pipeline_url: string | null;
            /** External Id */
            external_id: string | null;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** DeploymentUpdate */
        DeploymentUpdate: {
            /** Service Id */
            service_id?: string | null;
            /** Environment */
            environment?: ("development" | "staging" | "production") | null;
            /** External Id */
            external_id?: string | null;
            /** Kind */
            kind?: ("planned" | "remediation") | null;
            /** Release */
            release?: string | null;
            /** Head Sha */
            head_sha?: string | null;
            /** Status */
            status?: ("in_progress" | "succeeded" | "failed" | "rolled_back") | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Deployed By */
            deployed_by?: string | null;
            /** Pipeline Url */
            pipeline_url?: string | null;
            /** Commits */
            commits?: components["schemas"]["CommitIn"][] | null;
        };
        /** DoraSummary */
        DoraSummary: {
            window: components["schemas"]["Window"];
            filters: components["schemas"]["Filters"];
            /** Band Set */
            band_set: string;
            deployment_frequency: components["schemas"]["DeploymentFrequency"];
            change_lead_time: components["schemas"]["ChangeLeadTime"];
            change_fail_rate: components["schemas"]["ChangeFailRate"];
            failed_deployment_recovery_time: components["schemas"]["RecoveryTime"];
            deployment_rework_rate: components["schemas"]["ReworkRate"];
        };
        /** DoraTimeseries */
        DoraTimeseries: {
            window: components["schemas"]["Window"];
            filters: components["schemas"]["Filters"];
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "day" | "week" | "month";
            /** Points */
            points: components["schemas"]["TimeseriesPoint"][];
        };
        /** FailureCreate */
        FailureCreate: {
            /**
             * Deployment Id
             * Format: uuid
             */
            deployment_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "sev1" | "sev2" | "sev3" | "sev4";
            /** Summary */
            summary: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** External Ref */
            external_ref?: string | null;
        };
        /** FailureOut */
        FailureOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Deployment Id
             * Format: uuid
             */
            deployment_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "sev1" | "sev2" | "sev3" | "sev4";
            /** Summary */
            summary: string;
            /** Detected At */
            detected_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** External Ref */
            external_ref: string | null;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** FailureSummary */
        FailureSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "sev1" | "sev2" | "sev3" | "sev4";
            /** Summary */
            summary: string;
            /** Detected At */
            detected_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** FailureUpdate */
        FailureUpdate: {
            /** Deployment Id */
            deployment_id?: string | null;
            /** Severity */
            severity?: ("sev1" | "sev2" | "sev3" | "sev4") | null;
            /** Summary */
            summary?: string | null;
            /** Detected At */
            detected_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** External Ref */
            external_ref?: string | null;
        };
        /** FieldError */
        FieldError: {
            /** Location */
            location: string;
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** Filters */
        Filters: {
            /** Service Id */
            service_id: string | null;
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
        };
        /** IngestResult */
        IngestResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "staging" | "production";
            /**
             * Kind
             * @enum {string}
             */
            kind: "planned" | "remediation";
            /** Release */
            release: string;
            /** Head Sha */
            head_sha: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "succeeded" | "failed" | "rolled_back";
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Deployed By */
            deployed_by: string | null;
            /** Pipeline Url */
            pipeline_url: string | null;
            /** External Id */
            external_id: string | null;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Commits */
            commits: components["schemas"]["CommitOut"][];
            /** Failures */
            failures: components["schemas"]["FailureSummary"][];
            /**
             * Ignored
             * @description Set when the event was older than the deployment's current state and was ignored. Not an error: retries and out-of-order delivery are normal.
             */
            ignored?: "stale_event" | null;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Status */
            status: string;
        };
        /** Page[DeploymentOut] */
        Page_DeploymentOut_: {
            /** Items */
            items: components["schemas"]["DeploymentOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[FailureOut] */
        Page_FailureOut_: {
            /** Items */
            items: components["schemas"]["FailureOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ServiceOut] */
        Page_ServiceOut_: {
            /** Items */
            items: components["schemas"]["ServiceOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ProblemDetail */
        ProblemDetail: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks: {
                [key: string]: "ok" | "timeout" | "error";
            };
        };
        /** RecoveryTime */
        RecoveryTime: {
            /** Median Hours */
            median_hours: number | null;
            /** Sample Size */
            sample_size: number;
            /** Open Failures */
            open_failures: number;
            /** Band */
            band: ("elite" | "high" | "medium" | "low") | null;
        };
        /** ReworkRate */
        ReworkRate: {
            /** Rate */
            rate: number | null;
            /** Remediation Deployments */
            remediation_deployments: number;
            /** Total Deployments */
            total_deployments: number;
            /** Band */
            band: ("elite" | "high" | "medium" | "low") | null;
        };
        /** ServiceCreate */
        ServiceCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Owner Team */
            owner_team: string;
            /** Repo Url */
            repo_url?: string | null;
        };
        /** ServiceOut */
        ServiceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Owner Team */
            owner_team: string;
            /** Repo Url */
            repo_url: string | null;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ServiceUpdate */
        ServiceUpdate: {
            /** Slug */
            slug?: string | null;
            /** Name */
            name?: string | null;
            /** Owner Team */
            owner_team?: string | null;
            /** Repo Url */
            repo_url?: string | null;
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /** Start */
            start: string;
            /** Deployment Count */
            deployment_count: number;
            /** Median Lead Time Hours */
            median_lead_time_hours: number | null;
            /** Change Fail Rate */
            change_fail_rate: number | null;
            /** Median Recovery Hours */
            median_recovery_hours: number | null;
            /** Rework Rate */
            rework_rate: number | null;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Version */
            version: string;
            /** Git Sha */
            git_sha: string;
            /** Build Time */
            build_time: string;
        };
        /** Window */
        Window: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Days */
            days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    list_services_api_v1_services_get: {
        parameters: {
            query?: {
                owner_team?: string | null;
                /** @description Slug or name contains */
                q?: string | null;
                sort?: string;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ServiceOut_"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_service_api_v1_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_service_api_v1_services__service_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_service_api_v1_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Current ETag, e.g. "3". Required for writes. */
                "If-Match"?: string | null;
            };
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_service_api_v1_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description Current ETag, e.g. "3". Required for writes. */
                "If-Match"?: string | null;
            };
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_deployments_api_v1_deployments_get: {
        parameters: {
            query?: {
                service_id?: string | null;
                environment?: ("development" | "staging" | "production") | null;
                status?: ("in_progress" | "succeeded" | "failed" | "rolled_back") | null;
                kind?: ("planned" | "remediation") | null;
                /** @description started_at >= from (inclusive) */
                from?: string | null;
                /** @description started_at < to (exclusive) */
                to?: string | null;
                sort?: string;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeploymentOut_"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_deployment_api_v1_deployments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_deployment_api_v1_deployments__deployment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_deployment_api_v1_deployments__deployment_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Current ETag, e.g. "3". Required for writes. */
                "If-Match"?: string | null;
            };
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_deployment_api_v1_deployments__deployment_id__patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description Current ETag, e.g. "3". Required for writes. */
                "If-Match"?: string | null;
            };
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_failures_api_v1_failures_get: {
        parameters: {
            query?: {
                service_id?: string | null;
                deployment_id?: string | null;
                severity?: ("sev1" | "sev2" | "sev3" | "sev4") | null;
                /** @description true: unresolved; false: resolved */
                open?: boolean | null;
                sort?: string;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FailureOut_"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_failure_api_v1_failures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_failure_api_v1_failures__failure_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                failure_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_failure_api_v1_failures__failure_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Current ETag, e.g. "3". Required for writes. */
                "If-Match"?: string | null;
            };
            path: {
                failure_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_failure_api_v1_failures__failure_id__patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description Current ETag, e.g. "3". Required for writes. */
                "If-Match"?: string | null;
            };
            path: {
                failure_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailureUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    ingest_deployment_event_api_v1_events_deployments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Deployment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    dora_summary_api_v1_metrics_dora_get: {
        parameters: {
            query?: {
                /** @description Omit for org-wide metrics */
                service_id?: string | null;
                environment?: "development" | "staging" | "production";
                /** @description Window start (inclusive). Default: `to` minus 30 days */
                from?: string | null;
                /** @description Window end (exclusive). Default: now */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoraSummary"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    dora_timeseries_api_v1_metrics_dora_timeseries_get: {
        parameters: {
            query?: {
                /** @description Omit for org-wide metrics */
                service_id?: string | null;
                environment?: "development" | "staging" | "production";
                /** @description Window start (inclusive). Default: `to` minus 30 days */
                from?: string | null;
                /** @description Window end (exclusive). Default: now */
                to?: string | null;
                bucket?: "day" | "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoraTimeseries"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
