"""ORM models for the §6.2 reference DDL.

Enumerations are text + CHECK rather than native ENUMs (D3). Primary keys are
UUIDv7 generated by PostgreSQL 18's uuidv7() (D11).
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

ENVIRONMENTS = ("development", "staging", "production")
DEPLOYMENT_KINDS = ("planned", "remediation")
DEPLOYMENT_STATUSES = ("in_progress", "succeeded", "failed", "rolled_back")
LIVE_STATUSES = ("succeeded", "rolled_back")
SEVERITIES = ("sev1", "sev2", "sev3", "sev4")
SHA_PATTERN = "^[0-9a-f]{7,40}$"
SLUG_PATTERN = "^[a-z0-9][a-z0-9-]{1,62}$"


def _in(column: str, values: tuple[str, ...]) -> str:
    return f"{column} IN ({', '.join(repr(v) for v in values)})"


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(UUID(as_uuid=True), primary_key=True, server_default=text("uuidv7()"))


def _timestamp() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


class Service(Base):
    __tablename__ = "services"
    __table_args__ = (
        CheckConstraint(f"slug ~ '{SLUG_PATTERN}'", name="ck_services_slug"),
        CheckConstraint("length(name) BETWEEN 1 AND 200", name="ck_services_name"),
        CheckConstraint("length(owner_team) BETWEEN 1 AND 100", name="ck_services_owner_team"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    slug: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    owner_team: Mapped[str] = mapped_column(Text, nullable=False)
    repo_url: Mapped[str | None] = mapped_column(Text)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    created_at: Mapped[datetime] = _timestamp()
    updated_at: Mapped[datetime] = _timestamp()


class Deployment(Base):
    __tablename__ = "deployments"
    __table_args__ = (
        CheckConstraint(_in("environment", ENVIRONMENTS), name="ck_deployments_environment"),
        CheckConstraint(_in("kind", DEPLOYMENT_KINDS), name="ck_deployments_kind"),
        CheckConstraint("length(release) BETWEEN 1 AND 100", name="ck_deployments_release"),
        CheckConstraint(f"head_sha ~ '{SHA_PATTERN}'", name="ck_deployments_head_sha"),
        CheckConstraint(_in("status", DEPLOYMENT_STATUSES), name="ck_deployments_status"),
        CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name="finished_after_started"
        ),
        CheckConstraint(
            "status = 'in_progress' OR finished_at IS NOT NULL", name="terminal_has_finish"
        ),
        UniqueConstraint("service_id", "external_id", name="uq_service_external"),
        Index(
            "ix_deployments_live",
            "environment",
            "finished_at",
            "service_id",
            postgresql_where=text(_in("status", LIVE_STATUSES)),
        ),
        Index("ix_deployments_service_started", "service_id", text("started_at DESC")),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="RESTRICT"), nullable=False
    )
    environment: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'planned'"))
    release: Mapped[str] = mapped_column(Text, nullable=False)
    head_sha: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    deployed_by: Mapped[str | None] = mapped_column(Text)
    pipeline_url: Mapped[str | None] = mapped_column(Text)
    external_id: Mapped[str | None] = mapped_column(Text)  # pipeline run ID; idempotency key
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    created_at: Mapped[datetime] = _timestamp()
    updated_at: Mapped[datetime] = _timestamp()


class Commit(Base):
    __tablename__ = "commits"
    __table_args__ = (
        CheckConstraint(f"sha ~ '{SHA_PATTERN}'", name="ck_commits_sha"),
        UniqueConstraint("service_id", "sha", name="uq_service_sha"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="RESTRICT"), nullable=False
    )
    sha: Mapped[str] = mapped_column(Text, nullable=False)
    committed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    author: Mapped[str | None] = mapped_column(Text)
    message: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = _timestamp()


deployment_commits = Table(
    "deployment_commits",
    Base.metadata,
    Column(
        "deployment_id",
        UUID(as_uuid=True),
        ForeignKey("deployments.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "commit_id",
        UUID(as_uuid=True),
        ForeignKey("commits.id", ondelete="RESTRICT"),
        primary_key=True,
    ),
    Index("ix_deployment_commits_commit", "commit_id"),
)


class Failure(Base):
    __tablename__ = "failures"
    __table_args__ = (
        CheckConstraint(_in("severity", SEVERITIES), name="ck_failures_severity"),
        CheckConstraint("length(summary) BETWEEN 1 AND 500", name="ck_failures_summary"),
        CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= detected_at", name="resolved_after_detected"
        ),
        Index("ix_failures_deployment", "deployment_id"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    deployment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("deployments.id", ondelete="RESTRICT"), nullable=False
    )
    severity: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    external_ref: Mapped[str | None] = mapped_column(Text)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    created_at: Mapped[datetime] = _timestamp()
    updated_at: Mapped[datetime] = _timestamp()
